# Generated by Django 5.0.2 on 2024-03-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
