# Generated by Django 5.0.2 on 2024-03-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aha', '0003_alter_movie_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='aha/image')),
                ('video', models.FileField(upload_to='aha/videos')),
                ('cast', models.TextField()),
            ],
        ),
    ]
