# Generated by Django 5.0.6 on 2024-05-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('accountNo', models.BigIntegerField()),
                ('bankName', models.TextField()),
                ('IFSCcode', models.TextField()),
                ('cardNumber', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('expDate', models.DateField()),
                ('fixedAmount', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawlAmount', models.BigIntegerField(default=0)),
                ('depoistedAmount', models.BigIntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.account')),
            ],
        ),
    ]
